version: '3'
services:
  web_app:
    container_name: web_app
    env_file: ${E2E_ENV_FILE:-.env.production}
    build:
      context: .
      args:
        BUILD_STEP: app
        ENV_FILE: ${E2E_ENV_FILE:-.env.production}
        NPM_TOKEN: ${NPM_TOKEN}
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  cypress:
    image: cypress/included:9.5.1-node16.14.0-slim-chrome99-ff97
    env_file: ${E2E_ENV_FILE:-.env.production}
    depends_on:
      - web_app
    working_dir: /app
    environment:
      - CYPRESS_BASE_URL=${APP_BASE_URL:-http://web_app:4000}
      - NODE_ENV=production
    volumes:
      - ./:/app/
